export type ErrorCode =
	| 'INVALID_MESSAGE'
	| 'ROOM_NOT_FOUND'
	| 'NOT_JOINED'
	| 'NAME_REQUIRED'
	| 'NOT_FACILITATOR'
	| 'SPECTATOR_CANNOT_VOTE'
	| 'INVALID_CARD'
	| 'ALREADY_REVEALED'
	| 'NOT_REVEALED'
	| 'NO_VOTES'
	| 'ISSUE_NOT_FOUND'
	| 'PARTICIPANT_NOT_FOUND';
