import type { ErrorCode } from './errors';
import type { CardValue, DeckId, IssueInput, RoomState } from './model';

/**
 * Intents a client sends. The server validates them and answers with a fresh `state`
 * for everyone in the room, or an `error` to the sender.
 */
export type ClientMessage =
	/**
	 * Anyone. `sessionToken` is generated by the client and kept in the browser; joining again
	 * with the same token takes the same seat. It is a secret: never shown to other clients.
	 */
	| { type: 'join'; roomId: string; name: string; sessionToken: string }
	/** Non-spectators, while voting. `null` withdraws the vote. */
	| { type: 'vote'; value: CardValue | null }
	/** Facilitator. Reveals the cards. */
	| { type: 'flip' }
	/** Facilitator. Records the suggested estimate on the current issue, moves on and starts a new round. */
	| { type: 'reset' }
	/** Facilitator. Makes the issue current and starts a new round. */
	| { type: 'selectIssue'; issueId: string }
	/** Anyone. Quick add sends only `key` and `title`, the dialog sends all fields. */
	| { type: 'addIssue'; issue: IssueInput }
	/** Anyone. The estimate cannot be changed. */
	| { type: 'updateIssue'; issueId: string; changes: Partial<IssueInput> }
	/** Facilitator. */
	| { type: 'removeIssue'; issueId: string }
	/** Facilitator. Starts a new round with the new deck. */
	| { type: 'setDeck'; deckId: DeckId }
	/** The sender, for themselves. */
	| { type: 'setSpectator'; spectator: boolean }
	/** Facilitator. Turns flipping by itself on or off once everyone has voted. */
	| { type: 'setAutoFlip'; enabled: boolean }
	/** The sender, for themselves. Renames their seat; the seat, vote and role stay. */
	| { type: 'setName'; name: string }
	/** Facilitator. Hands the role to another participant. */
	| { type: 'transferFacilitator'; participantId: string };

/**
 * `state` goes to everyone in the room and is identical for all of them. The other messages go
 * to a single client only.
 */
export type ServerMessage =
	/**
	 * To the joining client: the seat its token maps to, and its vote in the current round, so a
	 * refresh while voting shows the picked card again.
	 */
	| { type: 'welcome'; participantId: string; myVote: CardValue | null }
	/** To everyone in the room after every change. */
	| { type: 'state'; room: RoomState }
	/**
	 * To the voter only, after each `vote`. Others learn only `hasVoted` until the flip. A new
	 * round sends no `myVote`: a `state` where the own seat has `hasVoted: false` means no vote.
	 */
	| { type: 'myVote'; value: CardValue | null }
	/** To the client whose intent failed. */
	| { type: 'error'; code: ErrorCode; message: string };
